/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as HealthRouteImport } from './routes/health'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as PublicContributeRouteImport } from './routes/_public.contribute'
import { Route as PublicDocumentsRouteImport } from './routes/_public.documents'
import { Route as PublicUpdatesRouteImport } from './routes/_public.updates'
import { Route as PublicContributeEditorRouteImport } from './routes/_public.contribute_.editor'
import { Route as PublicMapsMapIdRouteImport } from './routes/_public.maps.$mapId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContributeRoute = PublicContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDocumentsRoute = PublicDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PublicRoute,
} as any)
const PublicUpdatesRoute = PublicUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContributeEditorRoute = PublicContributeEditorRouteImport.update({
  id: '/contribute_/editor',
  path: '/contribute/editor',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMapsMapIdRoute = PublicMapsMapIdRouteImport.update({
  id: '/maps/$mapId',
  path: '/maps/$mapId',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/editor': typeof EditorRoute
  '/health': typeof HealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof PublicAboutRoute
  '/contribute': typeof PublicContributeRoute
  '/documents': typeof PublicDocumentsRoute
  '/updates': typeof PublicUpdatesRoute
  '/contribute/editor': typeof PublicContributeEditorRoute
  '/maps/$mapId': typeof PublicMapsMapIdRoute
}
export interface FileRoutesByTo {
  '/editor': typeof EditorRoute
  '/health': typeof HealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof PublicAboutRoute
  '/contribute': typeof PublicContributeRoute
  '/documents': typeof PublicDocumentsRoute
  '/updates': typeof PublicUpdatesRoute
  '/': typeof PublicIndexRoute
  '/contribute/editor': typeof PublicContributeEditorRoute
  '/maps/$mapId': typeof PublicMapsMapIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/editor': typeof EditorRoute
  '/health': typeof HealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/contribute': typeof PublicContributeRoute
  '/_public/documents': typeof PublicDocumentsRoute
  '/_public/updates': typeof PublicUpdatesRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/contribute_/editor': typeof PublicContributeEditorRoute
  '/_public/maps/$mapId': typeof PublicMapsMapIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor'
    | '/health'
    | '/sitemap.xml'
    | '/about'
    | '/contribute'
    | '/documents'
    | '/updates'
    | '/contribute/editor'
    | '/maps/$mapId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/editor'
    | '/health'
    | '/sitemap.xml'
    | '/about'
    | '/contribute'
    | '/documents'
    | '/updates'
    | '/'
    | '/contribute/editor'
    | '/maps/$mapId'
  id:
    | '__root__'
    | '/_public'
    | '/editor'
    | '/health'
    | '/sitemap.xml'
    | '/_public/about'
    | '/_public/contribute'
    | '/_public/documents'
    | '/_public/updates'
    | '/_public/'
    | '/_public/contribute_/editor'
    | '/_public/maps/$mapId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  EditorRoute: typeof EditorRoute
  HealthRoute: typeof HealthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contribute': {
      id: '/_public/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof PublicContributeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/documents': {
      id: '/_public/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof PublicDocumentsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/updates': {
      id: '/_public/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof PublicUpdatesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contribute_/editor': {
      id: '/_public/contribute_/editor'
      path: '/contribute/editor'
      fullPath: '/contribute/editor'
      preLoaderRoute: typeof PublicContributeEditorRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/maps/$mapId': {
      id: '/_public/maps/$mapId'
      path: '/maps/$mapId'
      fullPath: '/maps/$mapId'
      preLoaderRoute: typeof PublicMapsMapIdRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContributeRoute: typeof PublicContributeRoute
  PublicDocumentsRoute: typeof PublicDocumentsRoute
  PublicUpdatesRoute: typeof PublicUpdatesRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicContributeEditorRoute: typeof PublicContributeEditorRoute
  PublicMapsMapIdRoute: typeof PublicMapsMapIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContributeRoute: PublicContributeRoute,
  PublicDocumentsRoute: PublicDocumentsRoute,
  PublicUpdatesRoute: PublicUpdatesRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicContributeEditorRoute: PublicContributeEditorRoute,
  PublicMapsMapIdRoute: PublicMapsMapIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  EditorRoute: EditorRoute,
  HealthRoute: HealthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
